In [1]:
# This Python 3 environment comes with many helpful analytics libraries installed
# It is defined by the kaggle/python Docker image: https://github.com/kaggle/docker-python
# For example, here's several helpful packages to load

import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)

# Input data files are available in the read-only "../input/" directory
# For example, running this (by clicking run or pressing Shift+Enter) will list all files under the input directory

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))

# You can write up to 20GB to the current directory (/kaggle/working/) that gets preserved as output when you create a version using "Save & Run All" 
# You can also write temporary files to /kaggle/temp/, but they won't be saved outside of the current session

/kaggle/input/coasts-data/eastcoast.csv
/kaggle/input/coasts-data/westcoast.csv

In [2]:
westcoast=pd.read_csv('/kaggle/input/coasts-data/westcoast.csv')

In [3]:
westcoast

,location_id,latitude,longitude,elevation,coastline_distance(km),time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),is_day (),sunshine_duration (s)
0,0,19.156414,73.01383,12,14.29,1983-06-01T00:00,28.2,80,0.0,1008.9,1007.5,5.8,11.0,292,293,13.7,0,0.0
1,0,19.156414,73.01383,12,14.29,1983-06-01T06:00,27.3,89,0.1,1008.6,1007.2,4.6,7.3,288,290,10.4,1,0.0
2,0,19.156414,73.01383,12,14.29,1983-06-01T12:00,33.7,55,0.0,1008.3,1007.0,13.2,16.4,296,296,28.8,1,3600.0
3,0,19.156414,73.01383,12,14.29,1983-06-01T18:00,30.5,66,0.0,1005.9,1004.5,18.0,24.3,282,282,36.0,1,3600.0
4,0,19.156414,73.01383,12,14.29,1983-06-02T00:00,28.6,79,0.0,1007.6,1006.2,6.8,10.4,270,272,15.5,0,0.0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
460179,2,8.119508,77.52780,24,4.00,2023-09-29T18:00,23.7,94,4.8,1010.4,1007.6,19.7,30.3,298,298,33.8,0,0.0
460180,2,8.119508,77.52780,24,4.00,2023-09-30T00:00,23.5,91,1.2,1011.7,1008.9,19.0,29.8,285,288,32.8,0,0.0
460181,2,8.119508,77.52780,24,4.00,2023-09-30T06:00,24.6,93,0.1,1010.4,1007.6,16.0,25.5,279,279,27.4,1,0.0
460182,2,8.119508,77.52780,24,4.00,2023-09-30T12:00,28.0,77,2.8,1011.3,1008.6,25.6,33.6,272,274,49.3,1,3600.0
460183,2,8.119508,77.52780,24,4.00,2023-09-30T18:00,24.4,94,6.0,1010.5,1007.7,20.3,31.2,282,287,38.9,0,0.0

In [4]:
westcoast.nunique()

location_id                    10
latitude                       22
longitude                      23
elevation                      22
coastline_distance(km)         23
time                        20008
temperature_2m (°C)           285
relative_humidity_2m (%)       80
rain (mm)                    1264
pressure_msl (hPa)            266
surface_pressure (hPa)       1178
wind_speed_10m (km/h)         401
wind_speed_100m (km/h)        585
wind_direction_10m (°)        359
wind_direction_100m (°)       360
wind_gusts_10m (km/h)         257
is_day ()                       2
sunshine_duration (s)       65785
dtype: int64

In [5]:
westcoast.describe()

,location_id,latitude,longitude,elevation,coastline_distance(km),temperature_2m (°C),relative_humidity_2m (%),rain (mm),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),is_day (),sunshine_duration (s)
count,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000,460184.000000
mean,4.043478,14.036830,75.128685,437.434783,59.607391,23.828856,87.851594,2.821773,1008.565216,960.708716,12.209848,19.063745,250.745280,254.550071,29.978488,0.719806,1010.386182
std,2.941140,3.268881,1.320199,504.448402,46.406027,3.151445,10.570195,4.879485,2.434237,52.499290,5.969377,8.472038,54.565254,52.255599,12.156671,0.449095,1509.304892
min,0.000000,8.119508,73.013830,12.000000,1.180000,9.400000,18.000000,0.000000,991.100000,775.200000,0.000000,0.000000,1.000000,1.000000,1.400000,0.000000,0.000000
25%,1.000000,11.423550,73.969020,40.000000,6.210000,22.000000,83.000000,0.100000,1007.100000,934.200000,7.800000,13.000000,238.000000,241.000000,21.200000,0.000000,0.000000
50%,4.000000,13.884007,74.794520,418.000000,61.820000,24.000000,91.000000,1.000000,1008.700000,961.700000,11.800000,18.700000,255.000000,258.000000,29.500000,1.000000,0.000000
75%,7.000000,16.836554,76.632126,679.000000,101.740000,25.700000,95.000000,3.400000,1010.200000,1003.900000,16.100000,24.600000,278.000000,280.000000,38.200000,1.000000,2514.337500
max,9.000000,19.156414,77.527800,2219.000000,136.580000,38.600000,100.000000,206.600000,1020.600000,1013.100000,47.900000,73.400000,360.000000,360.000000,146.900000,1.000000,3600.000000

In [6]:
temp=[]
for i in range (westcoast.shape[0]):
    temp.append(0)

In [7]:
westcoast.loc[:, "Anomaly"] = temp

In [8]:
west_coast_anomaly=westcoast

In [9]:
temp=[]

In [10]:
west_coast_anomaly.shape[0]

460184

In [11]:
import warnings
warnings.simplefilter('ignore')
for i in range(west_coast_anomaly.shape[0]):
    if(west_coast_anomaly['rain (mm)'][i]>=40):
        list=[]
        west_coast_anomaly['Anomaly'][i]=1
        for j in westcoast.columns:
            list.append(west_coast_anomaly[j][i])
        temp.append(list)

In [12]:
df1=pd.DataFrame(temp)

In [13]:
df1

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0,19.156414,73.013830,12,14.29,1983-07-21T18:00,26.4,93,40.0,997.2,995.8,20.5,33.5,211,212,41.4,1,0.00,1
1,0,19.156414,73.013830,12,14.29,1983-08-15T06:00,25.4,94,41.5,1001.9,1000.5,14.5,25.1,276,278,31.3,1,0.00,1
2,0,19.156414,73.013830,12,14.29,1983-09-25T00:00,24.8,97,65.6,1005.6,1004.2,8.1,13.4,201,204,22.0,0,0.00,1
3,0,19.156414,73.013830,12,14.29,1984-06-16T00:00,26.2,93,48.7,997.1,995.7,25.7,41.5,226,227,56.9,0,0.00,1
4,0,19.156414,73.013830,12,14.29,1986-08-08T06:00,25.6,93,75.7,996.2,994.8,19.8,32.8,258,261,43.6,1,0.00,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
558,0,8.892795,76.632126,41,6.21,2022-08-01T12:00,24.3,94,44.1,1007.3,1002.6,14.8,21.1,256,256,26.6,1,0.00,1
559,0,8.892795,76.632126,41,6.21,2022-08-22T06:00,23.7,94,52.7,1009.4,1004.7,13.0,20.6,236,237,23.0,1,0.00,1
560,1,8.541301,76.921760,40,5.91,1988-06-04T12:00,24.9,96,40.8,1009.4,1004.8,15.4,18.9,254,252,28.4,1,1186.63,1
561,1,8.541301,76.921760,40,5.91,1991-06-03T00:00,24.7,98,79.2,1003.5,998.9,16.3,22.8,262,265,30.2,0,0.00,1
562,1,8.541301,76.921760,40,5.91,2010-08-15T18:00,22.6,97,49.0,1009.3,1004.6,17.2,24.1,250,248,33.5,1,0.00,1

In [14]:
import warnings
warnings.simplefilter('ignore')
for i in range(west_coast_anomaly.shape[0]):
    if((west_coast_anomaly['rain (mm)'][i]>=40) and (west_coast_anomaly['wind_speed_100m (km/h)'][i]>=40)):
        list=[]
        west_coast_anomaly['Anomaly'][i]=2
        for j in westcoast.columns:
            list.append(west_coast_anomaly[j][i])
        temp.append(list)

In [15]:
import warnings
warnings.simplefilter('ignore')

for i in range(west_coast_anomaly.shape[0]):
    if((west_coast_anomaly['temperature_2m (°C)'][i]>=31) and (west_coast_anomaly['relative_humidity_2m (%)'][i]>=65)):
        list=[]
        west_coast_anomaly['Anomaly'][i]=3
        for j in westcoast.columns:
            list.append(west_coast_anomaly[j][i])
        temp.append(list)

In [16]:
west_coast_anomaly.nunique()

location_id                    10
latitude                       22
longitude                      23
elevation                      22
coastline_distance(km)         23
time                        20008
temperature_2m (°C)           285
relative_humidity_2m (%)       80
rain (mm)                    1264
pressure_msl (hPa)            266
surface_pressure (hPa)       1178
wind_speed_10m (km/h)         401
wind_speed_100m (km/h)        585
wind_direction_10m (°)        359
wind_direction_100m (°)       360
wind_gusts_10m (km/h)         257
is_day ()                       2
sunshine_duration (s)       65785
Anomaly                         4
dtype: int64

In [17]:
df=pd.DataFrame(temp)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0,19.156414,73.01383,12,14.29,1983-07-21T18:00,26.4,93,40.0,997.2,995.8,20.5,33.5,211,212,41.4,1,0.0,1
1,0,19.156414,73.01383,12,14.29,1983-08-15T06:00,25.4,94,41.5,1001.9,1000.5,14.5,25.1,276,278,31.3,1,0.0,1
2,0,19.156414,73.01383,12,14.29,1983-09-25T00:00,24.8,97,65.6,1005.6,1004.2,8.1,13.4,201,204,22.0,0,0.0,1
3,0,19.156414,73.01383,12,14.29,1984-06-16T00:00,26.2,93,48.7,997.1,995.7,25.7,41.5,226,227,56.9,0,0.0,1
4,0,19.156414,73.01383,12,14.29,1986-08-08T06:00,25.6,93,75.7,996.2,994.8,19.8,32.8,258,261,43.6,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
1322,2,8.119508,77.52780,24,4.00,2019-06-19T12:00,31.0,65,0.2,1006.9,1004.2,33.5,45.2,274,276,65.9,1,3600.0,3
1323,2,8.119508,77.52780,24,4.00,2019-06-20T12:00,31.0,65,0.2,1006.9,1004.2,37.0,50.4,277,279,72.4,1,3600.0,3
1324,2,8.119508,77.52780,24,4.00,2020-06-09T12:00,31.1,66,0.0,1007.2,1004.5,32.1,43.4,279,282,63.7,1,3600.0,3
1325,2,8.119508,77.52780,24,4.00,2021-06-02T12:00,31.3,67,0.0,1006.7,1004.0,24.1,32.1,268,273,48.6,1,3600.0,3
1326,2,8.119508,77.52780,24,4.00,2023-06-01T12:00,31.1,65,0.2,1009.7,1007.0,27.4,35.2,251,252,55.1,1,3600.0,3

In [18]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1327 entries, 0 to 1326
Data columns (total 19 columns):
 #   Column  Non-Null Count  Dtype
---  ------  --------------  -----
 0   0       1327 non-null   int64
 1   1       1327 non-null   float64
 2   2       1327 non-null   float64
 3   3       1327 non-null   int64
 4   4       1327 non-null   float64
 5   5       1327 non-null   object
 6   6       1327 non-null   float64
 7   7       1327 non-null   int64
 8   8       1327 non-null   float64
 9   9       1327 non-null   float64
 10  10      1327 non-null   float64
 11  11      1327 non-null   float64
 12  12      1327 non-null   float64
 13  13      1327 non-null   int64
 14  14      1327 non-null   int64
 15  15      1327 non-null   float64
 16  16      1327 non-null   int64
 17  17      1327 non-null   float64
 18  18      1327 non-null   int64
dtypes: float64(11), int64(7), object(1)
memory usage: 197.1+ KB

In [19]:
d=west_coast_anomaly.sample(n=9000)
d

,location_id,latitude,longitude,elevation,coastline_distance(km),time,temperature_2m (°C),relative_humidity_2m (%),rain (mm),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),is_day (),sunshine_duration (s),Anomaly
439465,1,8.541301,76.921760,40,5.91,2022-08-06T06:00,23.7,93,1.8,1007.9,1003.3,14.2,23.8,324,322,34.2,1,0.0,0
114386,5,16.695957,74.183390,543,93.16,2012-07-19T12:00,23.3,89,7.3,1008.6,947.8,23.0,34.0,260,260,40.3,1,0.0,0
157834,7,16.836554,74.583730,547,128.56,2019-07-23T12:00,27.4,72,5.3,1004.7,944.5,20.0,27.3,252,254,46.8,1,3600.0,0
357917,7,11.423550,76.684494,2219,102.66,2019-07-24T06:00,13.6,99,1.6,1013.1,782.8,4.7,8.2,247,255,15.5,1,0.0,0
69741,3,16.977152,73.346115,53,1.18,2002-09-20T06:00,24.1,96,0.0,1012.7,1006.6,5.1,7.6,45,25,12.6,1,0.0,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
198228,9,15.922671,74.517960,731,93.41,2020-06-26T00:00,22.2,98,3.8,1007.4,926.3,12.0,20.2,263,266,25.2,0,0.0,0
75527,3,16.977152,73.346115,53,1.18,2014-09-02T18:00,26.7,90,2.4,1004.1,998.1,13.7,22.3,215,218,33.1,1,0.0,0
83704,4,17.680140,73.969020,679,91.89,1990-08-04T00:00,21.6,96,1.6,1010.8,934.8,9.4,16.5,247,250,28.1,0,0.0,0
237326,1,13.884007,75.593376,575,101.74,2018-07-10T12:00,24.1,88,3.9,1008.8,944.7,11.5,18.7,268,270,40.7,1,0.0,0
234265,1,13.884007,75.593376,575,101.74,2012-06-07T06:00,22.1,95,0.1,1007.2,942.8,13.5,21.7,236,234,24.5,1,0.0,0

In [20]:
for i in d.index:
    if(d['Anomaly'][i]==0):
        list=[]
        for j in d.columns:
            list.append(d[j][i])
        temp.append(list)

In [21]:
df=pd.DataFrame(temp)
df

,0,1,2,3,4,5,6,7,8,9,10,11,12,13,14,15,16,17,18
0,0,19.156414,73.013830,12,14.29,1983-07-21T18:00,26.4,93,40.0,997.2,995.8,20.5,33.5,211,212,41.4,1,0.0,1
1,0,19.156414,73.013830,12,14.29,1983-08-15T06:00,25.4,94,41.5,1001.9,1000.5,14.5,25.1,276,278,31.3,1,0.0,1
2,0,19.156414,73.013830,12,14.29,1983-09-25T00:00,24.8,97,65.6,1005.6,1004.2,8.1,13.4,201,204,22.0,0,0.0,1
3,0,19.156414,73.013830,12,14.29,1984-06-16T00:00,26.2,93,48.7,997.1,995.7,25.7,41.5,226,227,56.9,0,0.0,1
4,0,19.156414,73.013830,12,14.29,1986-08-08T06:00,25.6,93,75.7,996.2,994.8,19.8,32.8,258,261,43.6,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10290,9,15.922671,74.517960,731,93.41,2020-06-26T00:00,22.2,98,3.8,1007.4,926.3,12.0,20.2,263,266,25.2,0,0.0,0
10291,3,16.977152,73.346115,53,1.18,2014-09-02T18:00,26.7,90,2.4,1004.1,998.1,13.7,22.3,215,218,33.1,1,0.0,0
10292,4,17.680140,73.969020,679,91.89,1990-08-04T00:00,21.6,96,1.6,1010.8,934.8,9.4,16.5,247,250,28.1,0,0.0,0
10293,1,13.884007,75.593376,575,101.74,2018-07-10T12:00,24.1,88,3.9,1008.8,944.7,11.5,18.7,268,270,40.7,1,0.0,0
10294,1,13.884007,75.593376,575,101.74,2012-06-07T06:00,22.1,95,0.1,1007.2,942.8,13.5,21.7,236,234,24.5,1,0.0,0

In [22]:
west_coast_anomaly.columns

Index(['location_id', 'latitude', 'longitude', 'elevation',
       'coastline_distance(km)', 'time', 'temperature_2m (°C)',
       'relative_humidity_2m (%)', 'rain (mm)', 'pressure_msl (hPa)',
       'surface_pressure (hPa)', 'wind_speed_10m (km/h)',
       'wind_speed_100m (km/h)', 'wind_direction_10m (°)',
       'wind_direction_100m (°)', 'wind_gusts_10m (km/h)', 'is_day ()',
       'sunshine_duration (s)', 'Anomaly'],
      dtype='object')

In [23]:
df=df.rename(columns = {0:'location_id', 1:'latitude',2: 'longitude', 3:'elevation',
       4:'coastline_distance(km)', 5:'time', 6:'temperature_2m (°C)',
       7:'relative_humidity_2m (%)', 8:'rain (mm)', 9:'pressure_msl (hPa)',
       10:'surface_pressure (hPa)', 11:'wind_speed_10m (km/h)',
       12:'wind_speed_100m (km/h)', 13:'wind_direction_10m (°)',
       14:'wind_direction_100m (°)', 15:'wind_gusts_10m (km/h)', 16:'is_day ()',
       17:'sunshine_duration (s)', 18:'Anomaly'})

In [24]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 10295 entries, 0 to 10294
Data columns (total 19 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   location_id               10295 non-null  int64
 1   latitude                  10295 non-null  float64
 2   longitude                 10295 non-null  float64
 3   elevation                 10295 non-null  int64
 4   coastline_distance(km)    10295 non-null  float64
 5   time                      10295 non-null  object
 6   temperature_2m (°C)       10295 non-null  float64
 7   relative_humidity_2m (%)  10295 non-null  int64
 8   rain (mm)                 10295 non-null  float64
 9   pressure_msl (hPa)        10295 non-null  float64
 10  surface_pressure (hPa)    10295 non-null  float64
 11  wind_speed_10m (km/h)     10295 non-null  float64
 12  wind_speed_100m (km/h)    10295 non-null  float64
 13  wind_direction_10m (°)    10295 non-null  int64
 14  wind_direction_100m (°)   10295 non-null  int64
 15  wind_gusts_10m (km/h)     10295 non-null  float64
 16  is_day ()                 10295 non-null  int64
 17  sunshine_duration (s)     10295 non-null  float64
 18  Anomaly                   10295 non-null  int64
dtypes: float64(11), int64(7), object(1)
memory usage: 1.5+ MB

In [25]:
df=df.drop(['time'], axis=1)
df=df.drop(['location_id'],axis=1)

from sklearn.model_selection import GroupShuffleSplit 

splitter = GroupShuffleSplit(test_size=.30, n_splits=2, random_state = 15)
split = splitter.split(df, groups=df['Anomaly'])
train_inds, test_inds = next(split)

train = df.iloc[train_inds]
test = df.iloc[test_inds]

train

test

In [26]:
from sklearn.model_selection import train_test_split

In [27]:
y=df["Anomaly"]

In [28]:
x=df.drop("Anomaly",axis=1)

In [29]:
df

,latitude,longitude,elevation,coastline_distance(km),temperature_2m (°C),relative_humidity_2m (%),rain (mm),pressure_msl (hPa),surface_pressure (hPa),wind_speed_10m (km/h),wind_speed_100m (km/h),wind_direction_10m (°),wind_direction_100m (°),wind_gusts_10m (km/h),is_day (),sunshine_duration (s),Anomaly
0,19.156414,73.013830,12,14.29,26.4,93,40.0,997.2,995.8,20.5,33.5,211,212,41.4,1,0.0,1
1,19.156414,73.013830,12,14.29,25.4,94,41.5,1001.9,1000.5,14.5,25.1,276,278,31.3,1,0.0,1
2,19.156414,73.013830,12,14.29,24.8,97,65.6,1005.6,1004.2,8.1,13.4,201,204,22.0,0,0.0,1
3,19.156414,73.013830,12,14.29,26.2,93,48.7,997.1,995.7,25.7,41.5,226,227,56.9,0,0.0,1
4,19.156414,73.013830,12,14.29,25.6,93,75.7,996.2,994.8,19.8,32.8,258,261,43.6,1,0.0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
10290,15.922671,74.517960,731,93.41,22.2,98,3.8,1007.4,926.3,12.0,20.2,263,266,25.2,0,0.0,0
10291,16.977152,73.346115,53,1.18,26.7,90,2.4,1004.1,998.1,13.7,22.3,215,218,33.1,1,0.0,0
10292,17.680140,73.969020,679,91.89,21.6,96,1.6,1010.8,934.8,9.4,16.5,247,250,28.1,0,0.0,0
10293,13.884007,75.593376,575,101.74,24.1,88,3.9,1008.8,944.7,11.5,18.7,268,270,40.7,1,0.0,0
10294,13.884007,75.593376,575,101.74,22.1,95,0.1,1007.2,942.8,13.5,21.7,236,234,24.5,1,0.0,0

In [30]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.3,random_state=42)

In [31]:
from sklearn.preprocessing import StandardScaler
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(x_train)
X_test_scaled = scaler.transform(x_test)

In [32]:
x_train=X_train_scaled
x_test=X_test_scaled

In [33]:
from sklearn.neighbors import KNeighborsClassifier
from sklearn.svm import SVC
from sklearn.ensemble import GradientBoostingClassifier
from xgboost import XGBClassifier
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report

In [37]:
from sklearn.ensemble import RandomForestRegressor

x_train_RF, x_test_RF, y_train_RF, y_test_RF = x_train.values, x_test.values, y_train.values.ravel(), y_test.values.ravel()

In [39]:
Model_RF = RandomForestRegressor(n_estimators = 350,criterion='squared_error',random_state = 0,max_depth= 20,bootstrap =True)
# fit the regressor with x and y data
Model_RF.fit(x_train, y_train)
print("Random_forest Accuracy:{:.2f}%".format(Model_RF.score(x_test,y_test)*100))

Random_forest Accuracy:99.09%

In [40]:
from sklearn.tree import DecisionTreeRegressor
Model_DT = DecisionTreeRegressor(criterion='squared_error',random_state = 0,max_depth= 7,splitter='best')
Model_DT.fit(x_train, y_train)
print("DecisionTree Accuracy:{:.2f}%".format(Model_DT.score(x_test,y_test)*100))

DecisionTree Accuracy:99.07%

In [41]:
knn=KNeighborsClassifier()
knn.fit(x_train,y_train)
print("KNN Accuracy:{:.2f}%".format(knn.score(x_test,y_test)*100))

KNN Accuracy:97.70%

In [42]:
svm=SVC()
svm.fit(x_train,y_train)
print("SVM Accuracy:{:.2f}%".format(svm.score(x_test,y_test)*100))

SVM Accuracy:98.38%

In [43]:
gbc=GradientBoostingClassifier(subsample=0.5,n_estimators=450,max_depth=15,max_leaf_nodes=25)
gbc.fit(x_train,y_train)
print("Gradient Boosting Accuracy:{:.2f}%".format(gbc.score(x_test,y_test)*100))

Gradient Boosting Accuracy:99.03%

In [44]:
import warnings
warnings.filterwarnings('ignore')
xgb=XGBClassifier()
xgb.fit(x_train,y_train)
print("XGB Accuracy:{:.2f}%".format(xgb.score(x_test,y_test)*100))

XGB Accuracy:99.09%

In [45]:
input=[[19.156414,73.013830,12,14.29,25.4,94,41.5,1001.9,1000.5,14.5,25.1,276,278,13.3,1,0]]
ot=xgb.predict(input)
print("The weather is:")
if(ot==0):
    print("Normal")
elif(ot==1):
    print("Heavy Rain")
elif(ot==2):
    print("Storm")
elif(ot==3):
    print("Heat Wave")

The weather is:
Heat Wave

In [ ]:
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense
from tensorflow.keras.optimizers import Adam
from sklearn.preprocessing import StandardScaler

In [ ]:
X_train, X_test, y_train, y_test = train_test_split(x, y, test_size=0.2, random_state=42)

# Scale features
scaler = StandardScaler()
X_train_scaled = scaler.fit_transform(X_train)
X_test_scaled = scaler.transform(X_test)

In [ ]:
# Initialize the model
model = Sequential()

# Add input layer and first hidden layer
model.add(Dense(units=64, activation='relu', input_shape=(X_train_scaled.shape[1],)))

# Add second hidden layer
model.add(Dense(units=32, activation='relu'))

# Add output layer
model.add(Dense(units=1, activation='sigmoid'))

# Compile the model
model.compile(optimizer=Adam(learning_rate=0.001), loss='binary_crossentropy', metrics=['accuracy'])

In [ ]:
# Train the model
history = model.fit(X_train_scaled, y_train, epochs=100, batch_size=32, validation_split=0.2)

In [ ]:
# Evaluate on the test set
loss, accuracy = model.evaluate(X_test_scaled, y_test)
print(f'Test Accuracy: {accuracy:.2f}')